rssfeeds:
    image: asaito/rssfeeds
    links:
        - elasticsearch
    ports:
        - "18080:18080"

elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.bind_host=0.0.0.0
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - ${PWD}/esdata:/usr/share/elasticsearch/data
